[PatchSettings]
#Loading UTX - LOTUS.
LOADING_PATH=L2UI_CH3.skins.loading_

#MAX_ENCHANT - max enchant when enchanting an item.
MAX_ENCHANT=25

#LOGO_PATH - path to logo that will show on login screen and option window. (size 512x256 - centralized)
#Ex: LOGO_PATH=TexturePackage.TextureName 
LOGO_PATH=L2UI_CH3.LoginWnd.Logo_Classic-e

#BOTTOM_TEXT - text that will be shown in the footer on home screens.
BOTTOM_TEXT=Wellcome to Brproject - 2025

#Anuncios maximos Caracteres por linea.
AnunciosMaxCharacters=70

VentanaAnuncioWitdh=430
VentanaAnuncioHeigh=90

[Settings]
dsetup_ipserver=127.0.0.1

